easy_admin:
    site_name: 'ERC-MAP - Administration'
    entities:
       - App\Entity\TypeSource
       - App\Entity\CategorieSource
       - App\Entity\TypeSupport
       - App\Entity\CategorieSupport
       - App\Entity\Materiau
       - App\Entity\CategorieMateriau
       - App\Entity\Titre
       - App\Entity\Auteur
       - App\Entity\Langue
