# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        text_styling_only:
            toolbar: "basic_styles"
            uiColor: "#000000"
    toolbars:
        configs:
            basic_styles: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript' ]