# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        text_styling_only:
            toolbar: "basic_styles"
            uiColor: "#ffffff"
            height: '5rem'
            removePlugins: 'elementspath'
            blockless: true
            enterMode: 2
            resize_enabled: true
            resize_dir: 'vertical'
        styling_and_font:
            toolbar: "extra_font"
            uiColor: "#ffffff"
            height: '5rem'
            removePlugins: 'elementspath,a11y,a11yhelp'
            blockless: true
            enterMode: 2
            resize_enabled: true
            resize_dir: 'vertical'
            font_defaultLabel: 'Arial'
            font_names: 'Arial/Arial;IFAOGreek'
            contentsCss: '/build/ckeditor.css'
    toolbars:
        configs:
            basic_styles: ['@styles']
            extra_font: ['@styles', '-', '@font']
        items:
            styles: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript']
            font: ['Font', 'FontSize']